const firstNames = [
  "Abe",
  "Alex",
  "Alice",
  "Alexa",
  "Anna",
  "Bob",
  "Bill",
  "Beth",
  "Barb",
  "Bryce",
  "Bert",
  "Colin",
  "Carl",
  "Carol",
  "Cathy",
  "Chris",
  "Cesar",
  "Doug",
  "Devon",
  "Debra",
  "Eddie",
  "Eric",
  "Elly",
  "Edith",
  "Frank",
  "Fred",
  "Fran",
  "Fria",
  "Greg",
  "George",
  "Grant",
  "Gina",
  "Heidi",
  "Ivy",
  "Irv",
  "Jack",
  "Jill",
  "James",
  "Julie",
  "Kathy",
  "Kai",
  "Linda",
  "Mona",
  "Mark",
  "Matt",
  "Nia",
  "Nikki",
  "Nina",
  "Opal",
  "Olive",
  "Paul",
  "Pat",
  "Quinn",
  "Rick",
  "Ryan",
  "Rudy",
  "Ruth",
  "Sarah",
  "Saul",
  "Seth",
  "Tim",
  "Tina",
  "Tom",
  "Vinny",
  "Walt",
  "Zed",
];

const petNames = [
  "Abby",
  "Ace",
  "Angel",
  "Annie",
  "Apollo",
  "Bailey",
  "Bandit",
  "Baxter",
  "Bear",
  "Bella",
  "Belle",
  "Blue",
  "Bonnie",
  "Boomer",
  "Brutus",
  "Charlie",
  "Chloe",
  "Cleo",
  "Coco",
  "Cody",
  "Cooper",
  "Daisy",
  "Dixie",
  "Duke",
  "Fido",
  "Gatsby",
  "Ginger",
  "Gizmo",
  "Gracie",
  "Gus",
  "Gypsy",
  "Hunter",
  "Jack",
  "Jasper",
  "Jax",
  "Kiki",
  "Koda",
  "Lady",
  "Lily",
  "Lola",
  "Lou",
  "Louie",
  "Lucky",
  "Lucy",
  "Luna",
  "Maggie",
  "Max",
  "Maya",
  "Millie",
  "Murphy",
  "Nala",
  "Oliver",
  "Oreo",
  "Oscar",
  "Penny",
  "Pepper",
  "Pippin",
  "Poppy",
  "Pumpkin",
  "Rascal",
  "Riley",
  "Rocky",
  "Rosie",
  "Roxy",
  "Rusty",
  "Sadie",
  "Sammy",
  "Sassy",
  "Shadow",
  "Simba",
  "Sparky",
  "Sugar",
  "Teddy",
  "Thor",
  "Tilly",
  "Trixie",
  "Tucker",
  "Willow",
  "Winston",
  "Zeus",
  "Zoe",
];

const colors = [
  "red",
  "orange",
  "yellow",
  "lime",
  "green",
  "blue",
  "teal",
  "purple",
  "pink",
  "gray",
  "white",
  "black",
  "brown",
];
const space = [
  "Mars",
  "Venus",
  "Earth",
  "Saturn",
  "Uranus",
  "Pluto",
  "Moon",
  "Sun",
  "Stars",
];
const farmAnimals = [
  "cow",
  "horse",
  "donkey",
  "duck",
  "pig",
  "mule",
  "sheep",
  "lamb",
];

export const allCategories = [
  {
    CAR_AGE: {
      values: [1, 2, 3, 4, 5],
      descriptionTemplates: {
        leadingDescription: "The VALUE year old car",
        trailingDescription: "VALUE years old",
        diffGreaterDescription: "VALUE years older",
        diffLesserDescription: "VALUE years younger",
      },
    },
    CAR_MILES: {
      values: [10000, 20000, 30000, 40000, 50000],
      descriptionTemplates: {
        leadingDescription: "The car with VALUE miles",
        trailingDescription: "VALUE miles",
        diffGreaterDescription: "VALUE more miles",
        diffLesserDescription: "VALUE less miles",
        verb: "has",
      },
    },
    CAR_COLOR: {
      values: colors,
      descriptionTemplates: {
        leadingDescription: "The VALUE car",
        trailingDescription: "the VALUE car",
      },
    },
    NAME: {
      values: firstNames,
      descriptionTemplates: {
        leadingDescription: "VALUE's car",
        trailingDescription: "VALUE's car",
      },
    },
    CAR_MODEL: {
      values: ["Ford", "BMW", "Honda", "Mercedes", "Kia"],
      descriptionTemplates: {
        leadingDescription: "The VALUE",
        trailingDescription: "the VALUE",
      },
    },
  },
  {
    LANE: {
      values: [1, 2, 3, 4, 5, 6],
      descriptionTemplates: {
        leadingDescription: "The person who swam in lane VALUE",
        trailingDescription: "the person who swam in lane VALUE",
        diffGreaterDescription: "VALUE lane numbers higher",
        diffLesserDescription: "VALUE lane numbers lower",
        verb: "was",
      },
    },
    COLOR: {
      values: colors,
      descriptionTemplates: {
        leadingDescription: "The person wearing VALUE goggles",
        trailingDescription: "wearing VALUE goggles",
      },
    },
    NAME: {
      values: firstNames,
      descriptionTemplates: {
        leadingDescription: "VALUE",
        trailingDescription: "VALUE",
      },
    },
    STROKE: {
      values: ["fly", "back", "breast", "free", "IM"],
      descriptionTemplates: {
        leadingDescription: "The person who swam VALUE",
        trailingDescription: "the person who swam VALUE",
      },
    },
  },
  {
    TEST_SCORE: {
      values: [100, 95, 90, 85, 80],
      descriptionTemplates: {
        leadingDescription: "The person whose grade was VALUE",
        trailingDescription: "the person whose grade was VALUE",
        diffGreaterDescription: "VALUE points higher",
        diffLesserDescription: "VALUE points lower",
        verb: "scored",
      },
    },
    COLOR: {
      values: colors,
      descriptionTemplates: {
        leadingDescription: "The person using VALUE ink",
        trailingDescription: "using VALUE ink",
      },
    },
    NAME: {
      values: firstNames,
      descriptionTemplates: {
        leadingDescription: "VALUE",
        trailingDescription: "VALUE",
      },
    },
    SUBJECT: {
      values: [
        "dogs",
        "bats",
        "bugs",
        "corn",
        "Mars",
        "Venus",
        "Earth",
        "Saturn",
        "Uranus",
        "Pluto",
        "Moon",
        "Sun",
        "Stars",
        "cows",
        "wealth",
        "pigs",
        "geese",
        "sports",
        "cars",
        "bread",
        "pasta",
        "art",
        "music",
        "clouds",
        "rocks",
      ],
      descriptionTemplates: {
        leadingDescription: "The person who wrote about VALUE",
        trailingDescription: "the person who wrote about VALUE",
      },
    },
  },
  {
    NUMBER: {
      values: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      descriptionTemplates: {
        leadingDescription: "The person who ate VALUE s'mores",
        trailingDescription: "the person who ate VALUE s'mores",
        diffGreaterDescription: "VALUE more s'mores",
        diffLesserDescription: "VALUE less s'mores",
        verb: "ate",
      },
    },
    COLOR: {
      values: colors,
      descriptionTemplates: {
        leadingDescription: "The person with the VALUE sleeping bag",
        trailingDescription: "the person with the VALUE sleeping bag",
      },
    },
    NAME: {
      values: firstNames,
      descriptionTemplates: {
        leadingDescription: "VALUE",
        trailingDescription: "VALUE",
      },
    },
    CONSTELLATION: {
      values: [
        "Orion",
        "Gemini",
        "Leo",
        "Taurus",
        "Cygnus",
        "Lyra",
        "Pisces",
        "Aries",
        "Virgo",
        "Cancer",
      ],
      descriptionTemplates: {
        leadingDescription: "The person who spotted VALUE",
        trailingDescription: "the person who spotted VALUE",
      },
    },
  },
  {
    NUMBER: {
      values: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      descriptionTemplates: {
        leadingDescription: "The person who hiked VALUE miles",
        trailingDescription: "the person who hiked VALUE miles",
        diffGreaterDescription: "VALUE more miles",
        diffLesserDescription: "VALUE less miles",
        verb: "hiked",
      },
    },
    ELEVATION: {
      values: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
      descriptionTemplates: {
        leadingDescription: "The person who gained VALUE feet in elevation",
        trailingDescription: "the person who gained VALUE feet in elevation",
        diffGreaterDescription: "VALUE more feet",
        diffLesserDescription: "VALUE less feet",
        verb: "gained",
      },
    },
    DESTINATION: {
      values: [
        "lake",
        "river",
        "copse",
        "grove",
        "gully",
        "cliff",
        "stream",
        "creek",
        "forest",
        "hill",
        "ruins",
      ],
      descriptionTemplates: {
        leadingDescription: "The person who hiked to the VALUE",
        trailingDescription: "the person who hiked to the VALUE",
      },
    },
    NAME: {
      values: firstNames,
      descriptionTemplates: {
        leadingDescription: "VALUE",
        trailingDescription: "VALUE",
      },
    },
    ACCESSORY: {
      values: ["hat", "bottle", "poles", "glasses", "visor", "bandana"],
      descriptionTemplates: {
        leadingDescription: "The person with the VALUE",
        trailingDescription: "the person with the VALUE",
      },
    },
  },
  {
    HOURS: {
      values: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      descriptionTemplates: {
        leadingDescription: "The person who finished in VALUE hours",
        trailingDescription: "finished in VALUE hours",
        diffGreaterDescription: "VALUE more hours",
        diffLesserDescription: "VALUE less hours",
        verb: "took",
      },
    },
    PIECES: {
      values: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
      descriptionTemplates: {
        leadingDescription: "The person who did the VALUE piece puzzle",
        trailingDescription: "did the VALUE piece puzzle",
        diffGreaterDescription: "VALUE more pieces",
        diffLesserDescription: "VALUE less pieces",
        verb: "assembled",
      },
    },
    NAME: {
      values: firstNames,
      descriptionTemplates: {
        leadingDescription: "VALUE",
        trailingDescription: "VALUE",
      },
    },
    SUBJECT: {
      values: [
        "cats",
        "dogs",
        "frogs",
        "space",
        "cars",
        "cakes",
        "bread",
        "trees",
        "roses",
        "lilies",
        "horses",
        "toys",
        "cacti",
        "lilacs",
        "spices",
        "donuts",
        "candy",
        "trucks",
        "clouds",
        "clowns",
        "birds",
      ],
      descriptionTemplates: {
        leadingDescription: "The person who did a puzzle of VALUE",
        trailingDescription: "the person who did a puzzle of VALUE",
      },
    },
  },
  {
    TREES: {
      values: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      descriptionTemplates: {
        leadingDescription: "The house with VALUE trees",
        trailingDescription: "the house with VALUE trees",
        diffGreaterDescription: "VALUE more trees",
        diffLesserDescription: "VALUE less trees",
        verb: "has",
      },
    },
    NAME: {
      values: firstNames,
      descriptionTemplates: {
        leadingDescription: "VALUE's house",
        trailingDescription: "VALUE's house",
      },
    },
    COLOR: {
      values: colors,
      descriptionTemplates: {
        leadingDescription: "The VALUE house",
        trailingDescription: "the VALUE house",
      },
    },
    ACCESSORY: {
      values: [
        "swing",
        "dog",
        "cat",
        "fence",
        "chimney",
        "garden",
        "flag",
        "porch",
        "path",
        "tree",
      ],
      descriptionTemplates: {
        leadingDescription: "The house with the VALUE",
        trailingDescription: "the house with the VALUE",
      },
    },
  },
  {
    TIME: {
      values: [1, 2, 3, 4, 5],
      descriptionTemplates: {
        leadingDescription: "The person who snacks at VALUE o'clock",
        trailingDescription: "the person who snacks at VALUE o'clock",
        diffGreaterDescription: "VALUE hours more",
        diffLesserDescription: "VALUE hours less",
        verb: "snacks",
      },
    },
    DURATION: {
      values: [10, 15, 20, 25, 30],
      descriptionTemplates: {
        leadingDescription: "The person who takes VALUE minutes",
        trailingDescription: "the person who takes VALUE minutes",
        diffGreaterDescription: "VALUE minutes more",
        diffLesserDescription: "VALUE minutes less",
        verb: "takes",
      },
    },
    NAME: {
      values: firstNames,
      descriptionTemplates: {
        leadingDescription: "VALUE",
        trailingDescription: "VALUE",
      },
    },
    COLOR: {
      values: colors,
      descriptionTemplates: {
        leadingDescription: "The person with the VALUE cup",
        trailingDescription: "the person with the VALUE cup",
      },
    },
    DRINK: {
      values: ["tea", "coffee", "water", "milk", "wine", "beer", "juice"],
      descriptionTemplates: {
        leadingDescription: "The person who drinks VALUE",
        trailingDescription: "the person who drinks VALUE",
      },
    },
    SNACK: {
      values: ["apple", "cookie", "bun", "pear", "donut", "banana"],
      descriptionTemplates: {
        leadingDescription: "The person who eats the VALUE",
        trailingDescription: "the person who eats the VALUE",
      },
    },
  },
  // {
  //   NUMBER_WON: {
  //     values: [1,2,3,4,5],
  //     descriptionTemplates: {
  //       leadingDescription: "The person who won VALUE games",
  //       trailingDescription: "the person who won VALUE games",
  //       diffGreaterDescription: "VALUE more games",
  //       diffLesserDescription: "VALUE more games",
  //       verb: "won",
  //     },
  //   },
  //   NAME: {
  //     values: firstNames,
  //     descriptionTemplates: {
  //       leadingDescription: "VALUE",
  //       trailingDescription: "VALUE",
  //     },
  //   },
  //   GAME: {
  //     values: ["Plague","Hanabi","Dixit","Boggle","Botanik","Kokoro","Cards"],
  //     descriptionTemplates: {
  //       leadingDescription: "The person who likes VALUE",
  //       trailingDescription: "the person who likes VALUE",
  //     },
  //   },
  // },
];
