import {allCategories} from "./allCategories";

function arrayValuesAreUniqueQ(array) {
  const uniqueArray = Array.from(new Set(array));
  return array.length === uniqueArray.length;
}

function arraysDoNotOverlapQ(...arrays) {
  // Get rid of unique values within each array before comparing
  const uniqueArrays = arrays.map((array) => Array.from(new Set(array)));
  // Combine all unique arrays
  const combinedArray = [].concat(...uniqueArrays);

  // Create a unique combined array
  const uniqueCombinedArray = Array.from(new Set(combinedArray));

  // Check if the combined array has the same length as the unique combined array
  return uniqueCombinedArray.length === combinedArray.length;
}

describe("allCategories: tests per scenario", () => {
  allCategories.forEach((scenario, index) => {
    test(`Scenario ${index} with keys ${Object.keys(
      scenario,
    )} has values that are unique across categories`, () => {
      const allValues = Object.keys(scenario).map(
        (category) => scenario[category].values,
      );
      const valuesAreUniqueAcrossCategories = arraysDoNotOverlapQ(...allValues);
      expect(valuesAreUniqueAcrossCategories).toBe(true);
    });

    test(`Scenario ${index} with keys ${Object.keys(
      scenario,
    )} has at least 4 categories`, () => {
      expect(Object.keys(scenario).length).toBeGreaterThanOrEqual(4);
    });

    for (const category in scenario) {
      test(`Scenario ${index} with keys ${Object.keys(
        scenario,
      )} for key ${category} has values that are unique within each category`, () => {
        expect(arrayValuesAreUniqueQ(scenario[category].values)).toBe(true);
      });

      test(`Scenario ${index} with keys ${Object.keys(
        scenario,
      )} for key ${category} has at least 5 values`, () => {
        expect(scenario[category].values.length).toBeGreaterThanOrEqual(5);
      });

      test(`Scenario ${index} with keys ${Object.keys(
        scenario,
      )} for key ${category} uses the value in every description`, () => {
        for (const template in scenario[category].descriptionTemplates) {
          if (template === "verb") continue;
          const generatedDescription =
            scenario[category].descriptionTemplates[template]("X_TEST_VALUE");
          expect(generatedDescription).toContain("X_TEST_VALUE");
        }
      });

      test(`Scenario ${index} with keys ${Object.keys(
        scenario,
      )} for key ${category} has the expected description templates`, () => {
        if (typeof scenario[category].values[0] === "number") {
          expect(scenario[category].descriptionTemplates).toHaveProperty(
            "diffLesserDescription",
          );
          expect(scenario[category].descriptionTemplates).toHaveProperty(
            "diffGreaterDescription",
          );
        }
        expect(scenario[category].descriptionTemplates).toHaveProperty(
          "description",
        );
      });
    }
  });
});

describe("allCategories example text", () => {
  test("A sampling of clue text", () => {
    let descriptions = [];
    allCategories.forEach((scenario) => {
      for (const labelA in scenario) {
        const valueA = scenario[labelA].values[0];
        const templatesA = scenario[labelA].descriptionTemplates;
        for (const labelB in scenario) {
          if (labelA === labelB) continue;
          const valueB = scenario[labelB].values[0];
          const valueB2 = scenario[labelB].values[1];
          const templatesB = scenario[labelB].descriptionTemplates;
          const leadingDescription = templatesA.description(valueA);
          const trailingDescription = templatesB.description(valueB);
          const trailingDescription2 = templatesB.description(valueB2);
          descriptions = [
            ...descriptions,
            `${leadingDescription} is not ${trailingDescription}.`,
          ];
          descriptions = [
            ...descriptions,
            `${leadingDescription} is ${trailingDescription} or ${trailingDescription2}.`,
          ];
          if (typeof valueB != "number") continue;
          const numericGreaterDescription =
            templatesB.diffGreaterDescription(valueB);
          const numericLesserDescription =
            templatesB.diffLesserDescription(valueB);
          const numericSomeDescription =
            templatesB.diffGreaterDescription("some");
          const numericComparisonVerb = templatesB.verb || "is";
          descriptions = [
            ...descriptions,
            `${leadingDescription} ${numericComparisonVerb} at least ${numericGreaterDescription} than ${trailingDescription}.`,
          ];
          descriptions = [
            ...descriptions,
            `${leadingDescription} ${numericComparisonVerb} at least ${numericLesserDescription} than ${trailingDescription}.`,
          ];
          descriptions = [
            ...descriptions,
            `${leadingDescription} ${numericComparisonVerb} ${numericSomeDescription} than ${trailingDescription}.`,
          ];
        }
      }
    });
    expect(descriptions).toMatchInlineSnapshot(`
      [
        "the 1 year old car is not the car with 10000 miles.",
        "the 1 year old car is the car with 10000 miles or the car with 20000 miles.",
        "the 1 year old car has at least 10000 more miles than the car with 10000 miles.",
        "the 1 year old car has at least 10000 less miles than the car with 10000 miles.",
        "the 1 year old car has some more miles than the car with 10000 miles.",
        "the 1 year old car is not the red car.",
        "the 1 year old car is the red car or the orange car.",
        "the 1 year old car is not Aaron's car.",
        "the 1 year old car is Aaron's car or Abby's car.",
        "the 1 year old car is not the Ford.",
        "the 1 year old car is the Ford or the BMW.",
        "the car with 10000 miles is not the 1 year old car.",
        "the car with 10000 miles is the 1 year old car or the 2 year old car.",
        "the car with 10000 miles is at least 1 years older than the 1 year old car.",
        "the car with 10000 miles is at least 1 years younger than the 1 year old car.",
        "the car with 10000 miles is some years older than the 1 year old car.",
        "the car with 10000 miles is not the red car.",
        "the car with 10000 miles is the red car or the orange car.",
        "the car with 10000 miles is not Aaron's car.",
        "the car with 10000 miles is Aaron's car or Abby's car.",
        "the car with 10000 miles is not the Ford.",
        "the car with 10000 miles is the Ford or the BMW.",
        "the red car is not the 1 year old car.",
        "the red car is the 1 year old car or the 2 year old car.",
        "the red car is at least 1 years older than the 1 year old car.",
        "the red car is at least 1 years younger than the 1 year old car.",
        "the red car is some years older than the 1 year old car.",
        "the red car is not the car with 10000 miles.",
        "the red car is the car with 10000 miles or the car with 20000 miles.",
        "the red car has at least 10000 more miles than the car with 10000 miles.",
        "the red car has at least 10000 less miles than the car with 10000 miles.",
        "the red car has some more miles than the car with 10000 miles.",
        "the red car is not Aaron's car.",
        "the red car is Aaron's car or Abby's car.",
        "the red car is not the Ford.",
        "the red car is the Ford or the BMW.",
        "Aaron's car is not the 1 year old car.",
        "Aaron's car is the 1 year old car or the 2 year old car.",
        "Aaron's car is at least 1 years older than the 1 year old car.",
        "Aaron's car is at least 1 years younger than the 1 year old car.",
        "Aaron's car is some years older than the 1 year old car.",
        "Aaron's car is not the car with 10000 miles.",
        "Aaron's car is the car with 10000 miles or the car with 20000 miles.",
        "Aaron's car has at least 10000 more miles than the car with 10000 miles.",
        "Aaron's car has at least 10000 less miles than the car with 10000 miles.",
        "Aaron's car has some more miles than the car with 10000 miles.",
        "Aaron's car is not the red car.",
        "Aaron's car is the red car or the orange car.",
        "Aaron's car is not the Ford.",
        "Aaron's car is the Ford or the BMW.",
        "the Ford is not the 1 year old car.",
        "the Ford is the 1 year old car or the 2 year old car.",
        "the Ford is at least 1 years older than the 1 year old car.",
        "the Ford is at least 1 years younger than the 1 year old car.",
        "the Ford is some years older than the 1 year old car.",
        "the Ford is not the car with 10000 miles.",
        "the Ford is the car with 10000 miles or the car with 20000 miles.",
        "the Ford has at least 10000 more miles than the car with 10000 miles.",
        "the Ford has at least 10000 less miles than the car with 10000 miles.",
        "the Ford has some more miles than the car with 10000 miles.",
        "the Ford is not the red car.",
        "the Ford is the red car or the orange car.",
        "the Ford is not Aaron's car.",
        "the Ford is Aaron's car or Abby's car.",
        "the person who swam in lane 1 is not the person wearing red goggles.",
        "the person who swam in lane 1 is the person wearing red goggles or the person wearing orange goggles.",
        "the person who swam in lane 1 is not Aaron.",
        "the person who swam in lane 1 is Aaron or Abby.",
        "the person who swam in lane 1 is not the person who swam fly.",
        "the person who swam in lane 1 is the person who swam fly or the person who swam back.",
        "the person wearing red goggles is not the person who swam in lane 1.",
        "the person wearing red goggles is the person who swam in lane 1 or the person who swam in lane 2.",
        "the person wearing red goggles was at least 1 lane numbers higher than the person who swam in lane 1.",
        "the person wearing red goggles was at least 1 lane numbers lower than the person who swam in lane 1.",
        "the person wearing red goggles was some lane numbers higher than the person who swam in lane 1.",
        "the person wearing red goggles is not Aaron.",
        "the person wearing red goggles is Aaron or Abby.",
        "the person wearing red goggles is not the person who swam fly.",
        "the person wearing red goggles is the person who swam fly or the person who swam back.",
        "Aaron is not the person who swam in lane 1.",
        "Aaron is the person who swam in lane 1 or the person who swam in lane 2.",
        "Aaron was at least 1 lane numbers higher than the person who swam in lane 1.",
        "Aaron was at least 1 lane numbers lower than the person who swam in lane 1.",
        "Aaron was some lane numbers higher than the person who swam in lane 1.",
        "Aaron is not the person wearing red goggles.",
        "Aaron is the person wearing red goggles or the person wearing orange goggles.",
        "Aaron is not the person who swam fly.",
        "Aaron is the person who swam fly or the person who swam back.",
        "the person who swam fly is not the person who swam in lane 1.",
        "the person who swam fly is the person who swam in lane 1 or the person who swam in lane 2.",
        "the person who swam fly was at least 1 lane numbers higher than the person who swam in lane 1.",
        "the person who swam fly was at least 1 lane numbers lower than the person who swam in lane 1.",
        "the person who swam fly was some lane numbers higher than the person who swam in lane 1.",
        "the person who swam fly is not the person wearing red goggles.",
        "the person who swam fly is the person wearing red goggles or the person wearing orange goggles.",
        "the person who swam fly is not Aaron.",
        "the person who swam fly is Aaron or Abby.",
        "the person whose grade was 100 is not the person using red ink.",
        "the person whose grade was 100 is the person using red ink or the person using orange ink.",
        "the person whose grade was 100 is not Aaron.",
        "the person whose grade was 100 is Aaron or Abby.",
        "the person whose grade was 100 is not the person who wrote about dogs.",
        "the person whose grade was 100 is the person who wrote about dogs or the person who wrote about bats.",
        "the person using red ink is not the person whose grade was 100.",
        "the person using red ink is the person whose grade was 100 or the person whose grade was 95.",
        "the person using red ink scored at least 100 points higher than the person whose grade was 100.",
        "the person using red ink scored at least 100 points lower than the person whose grade was 100.",
        "the person using red ink scored some points higher than the person whose grade was 100.",
        "the person using red ink is not Aaron.",
        "the person using red ink is Aaron or Abby.",
        "the person using red ink is not the person who wrote about dogs.",
        "the person using red ink is the person who wrote about dogs or the person who wrote about bats.",
        "Aaron is not the person whose grade was 100.",
        "Aaron is the person whose grade was 100 or the person whose grade was 95.",
        "Aaron scored at least 100 points higher than the person whose grade was 100.",
        "Aaron scored at least 100 points lower than the person whose grade was 100.",
        "Aaron scored some points higher than the person whose grade was 100.",
        "Aaron is not the person using red ink.",
        "Aaron is the person using red ink or the person using orange ink.",
        "Aaron is not the person who wrote about dogs.",
        "Aaron is the person who wrote about dogs or the person who wrote about bats.",
        "the person who wrote about dogs is not the person whose grade was 100.",
        "the person who wrote about dogs is the person whose grade was 100 or the person whose grade was 95.",
        "the person who wrote about dogs scored at least 100 points higher than the person whose grade was 100.",
        "the person who wrote about dogs scored at least 100 points lower than the person whose grade was 100.",
        "the person who wrote about dogs scored some points higher than the person whose grade was 100.",
        "the person who wrote about dogs is not the person using red ink.",
        "the person who wrote about dogs is the person using red ink or the person using orange ink.",
        "the person who wrote about dogs is not Aaron.",
        "the person who wrote about dogs is Aaron or Abby.",
        "the person who ate 1 s'mores is not the person with the red sleeping bag.",
        "the person who ate 1 s'mores is the person with the red sleeping bag or the person with the orange sleeping bag.",
        "the person who ate 1 s'mores is not Aaron.",
        "the person who ate 1 s'mores is Aaron or Abby.",
        "the person who ate 1 s'mores is not the person who spotted Orion.",
        "the person who ate 1 s'mores is the person who spotted Orion or the person who spotted Gemini.",
        "the person with the red sleeping bag is not the person who ate 1 s'mores.",
        "the person with the red sleeping bag is the person who ate 1 s'mores or the person who ate 2 s'mores.",
        "the person with the red sleeping bag ate at least 1 more s'mores than the person who ate 1 s'mores.",
        "the person with the red sleeping bag ate at least 1 less s'mores than the person who ate 1 s'mores.",
        "the person with the red sleeping bag ate some more s'mores than the person who ate 1 s'mores.",
        "the person with the red sleeping bag is not Aaron.",
        "the person with the red sleeping bag is Aaron or Abby.",
        "the person with the red sleeping bag is not the person who spotted Orion.",
        "the person with the red sleeping bag is the person who spotted Orion or the person who spotted Gemini.",
        "Aaron is not the person who ate 1 s'mores.",
        "Aaron is the person who ate 1 s'mores or the person who ate 2 s'mores.",
        "Aaron ate at least 1 more s'mores than the person who ate 1 s'mores.",
        "Aaron ate at least 1 less s'mores than the person who ate 1 s'mores.",
        "Aaron ate some more s'mores than the person who ate 1 s'mores.",
        "Aaron is not the person with the red sleeping bag.",
        "Aaron is the person with the red sleeping bag or the person with the orange sleeping bag.",
        "Aaron is not the person who spotted Orion.",
        "Aaron is the person who spotted Orion or the person who spotted Gemini.",
        "the person who spotted Orion is not the person who ate 1 s'mores.",
        "the person who spotted Orion is the person who ate 1 s'mores or the person who ate 2 s'mores.",
        "the person who spotted Orion ate at least 1 more s'mores than the person who ate 1 s'mores.",
        "the person who spotted Orion ate at least 1 less s'mores than the person who ate 1 s'mores.",
        "the person who spotted Orion ate some more s'mores than the person who ate 1 s'mores.",
        "the person who spotted Orion is not the person with the red sleeping bag.",
        "the person who spotted Orion is the person with the red sleeping bag or the person with the orange sleeping bag.",
        "the person who spotted Orion is not Aaron.",
        "the person who spotted Orion is Aaron or Abby.",
        "the person who hiked 1 miles is not the person who gained 100 feet in elevation.",
        "the person who hiked 1 miles is the person who gained 100 feet in elevation or the person who gained 200 feet in elevation.",
        "the person who hiked 1 miles gained at least 100 more feet than the person who gained 100 feet in elevation.",
        "the person who hiked 1 miles gained at least 100 less feet than the person who gained 100 feet in elevation.",
        "the person who hiked 1 miles gained some more feet than the person who gained 100 feet in elevation.",
        "the person who hiked 1 miles is not the person who hiked to the lake.",
        "the person who hiked 1 miles is the person who hiked to the lake or the person who hiked to the river.",
        "the person who hiked 1 miles is not Aaron.",
        "the person who hiked 1 miles is Aaron or Abby.",
        "the person who hiked 1 miles is not the person with the hat.",
        "the person who hiked 1 miles is the person with the hat or the person with the bottle.",
        "the person who gained 100 feet in elevation is not the person who hiked 1 miles.",
        "the person who gained 100 feet in elevation is the person who hiked 1 miles or the person who hiked 2 miles.",
        "the person who gained 100 feet in elevation hiked at least 1 more miles than the person who hiked 1 miles.",
        "the person who gained 100 feet in elevation hiked at least 1 less miles than the person who hiked 1 miles.",
        "the person who gained 100 feet in elevation hiked some more miles than the person who hiked 1 miles.",
        "the person who gained 100 feet in elevation is not the person who hiked to the lake.",
        "the person who gained 100 feet in elevation is the person who hiked to the lake or the person who hiked to the river.",
        "the person who gained 100 feet in elevation is not Aaron.",
        "the person who gained 100 feet in elevation is Aaron or Abby.",
        "the person who gained 100 feet in elevation is not the person with the hat.",
        "the person who gained 100 feet in elevation is the person with the hat or the person with the bottle.",
        "the person who hiked to the lake is not the person who hiked 1 miles.",
        "the person who hiked to the lake is the person who hiked 1 miles or the person who hiked 2 miles.",
        "the person who hiked to the lake hiked at least 1 more miles than the person who hiked 1 miles.",
        "the person who hiked to the lake hiked at least 1 less miles than the person who hiked 1 miles.",
        "the person who hiked to the lake hiked some more miles than the person who hiked 1 miles.",
        "the person who hiked to the lake is not the person who gained 100 feet in elevation.",
        "the person who hiked to the lake is the person who gained 100 feet in elevation or the person who gained 200 feet in elevation.",
        "the person who hiked to the lake gained at least 100 more feet than the person who gained 100 feet in elevation.",
        "the person who hiked to the lake gained at least 100 less feet than the person who gained 100 feet in elevation.",
        "the person who hiked to the lake gained some more feet than the person who gained 100 feet in elevation.",
        "the person who hiked to the lake is not Aaron.",
        "the person who hiked to the lake is Aaron or Abby.",
        "the person who hiked to the lake is not the person with the hat.",
        "the person who hiked to the lake is the person with the hat or the person with the bottle.",
        "Aaron is not the person who hiked 1 miles.",
        "Aaron is the person who hiked 1 miles or the person who hiked 2 miles.",
        "Aaron hiked at least 1 more miles than the person who hiked 1 miles.",
        "Aaron hiked at least 1 less miles than the person who hiked 1 miles.",
        "Aaron hiked some more miles than the person who hiked 1 miles.",
        "Aaron is not the person who gained 100 feet in elevation.",
        "Aaron is the person who gained 100 feet in elevation or the person who gained 200 feet in elevation.",
        "Aaron gained at least 100 more feet than the person who gained 100 feet in elevation.",
        "Aaron gained at least 100 less feet than the person who gained 100 feet in elevation.",
        "Aaron gained some more feet than the person who gained 100 feet in elevation.",
        "Aaron is not the person who hiked to the lake.",
        "Aaron is the person who hiked to the lake or the person who hiked to the river.",
        "Aaron is not the person with the hat.",
        "Aaron is the person with the hat or the person with the bottle.",
        "the person with the hat is not the person who hiked 1 miles.",
        "the person with the hat is the person who hiked 1 miles or the person who hiked 2 miles.",
        "the person with the hat hiked at least 1 more miles than the person who hiked 1 miles.",
        "the person with the hat hiked at least 1 less miles than the person who hiked 1 miles.",
        "the person with the hat hiked some more miles than the person who hiked 1 miles.",
        "the person with the hat is not the person who gained 100 feet in elevation.",
        "the person with the hat is the person who gained 100 feet in elevation or the person who gained 200 feet in elevation.",
        "the person with the hat gained at least 100 more feet than the person who gained 100 feet in elevation.",
        "the person with the hat gained at least 100 less feet than the person who gained 100 feet in elevation.",
        "the person with the hat gained some more feet than the person who gained 100 feet in elevation.",
        "the person with the hat is not the person who hiked to the lake.",
        "the person with the hat is the person who hiked to the lake or the person who hiked to the river.",
        "the person with the hat is not Aaron.",
        "the person with the hat is Aaron or Abby.",
        "the person who finished in 1 hours is not the person who did the 100 piece puzzle.",
        "the person who finished in 1 hours is the person who did the 100 piece puzzle or the person who did the 200 piece puzzle.",
        "the person who finished in 1 hours assembled at least 100 more pieces than the person who did the 100 piece puzzle.",
        "the person who finished in 1 hours assembled at least 100 less pieces than the person who did the 100 piece puzzle.",
        "the person who finished in 1 hours assembled some more pieces than the person who did the 100 piece puzzle.",
        "the person who finished in 1 hours is not Aaron.",
        "the person who finished in 1 hours is Aaron or Abby.",
        "the person who finished in 1 hours is not the person who did a puzzle of cats.",
        "the person who finished in 1 hours is the person who did a puzzle of cats or the person who did a puzzle of dogs.",
        "the person who did the 100 piece puzzle is not the person who finished in 1 hours.",
        "the person who did the 100 piece puzzle is the person who finished in 1 hours or the person who finished in 2 hours.",
        "the person who did the 100 piece puzzle took at least 1 more hours than the person who finished in 1 hours.",
        "the person who did the 100 piece puzzle took at least 1 less hours than the person who finished in 1 hours.",
        "the person who did the 100 piece puzzle took some more hours than the person who finished in 1 hours.",
        "the person who did the 100 piece puzzle is not Aaron.",
        "the person who did the 100 piece puzzle is Aaron or Abby.",
        "the person who did the 100 piece puzzle is not the person who did a puzzle of cats.",
        "the person who did the 100 piece puzzle is the person who did a puzzle of cats or the person who did a puzzle of dogs.",
        "Aaron is not the person who finished in 1 hours.",
        "Aaron is the person who finished in 1 hours or the person who finished in 2 hours.",
        "Aaron took at least 1 more hours than the person who finished in 1 hours.",
        "Aaron took at least 1 less hours than the person who finished in 1 hours.",
        "Aaron took some more hours than the person who finished in 1 hours.",
        "Aaron is not the person who did the 100 piece puzzle.",
        "Aaron is the person who did the 100 piece puzzle or the person who did the 200 piece puzzle.",
        "Aaron assembled at least 100 more pieces than the person who did the 100 piece puzzle.",
        "Aaron assembled at least 100 less pieces than the person who did the 100 piece puzzle.",
        "Aaron assembled some more pieces than the person who did the 100 piece puzzle.",
        "Aaron is not the person who did a puzzle of cats.",
        "Aaron is the person who did a puzzle of cats or the person who did a puzzle of dogs.",
        "the person who did a puzzle of cats is not the person who finished in 1 hours.",
        "the person who did a puzzle of cats is the person who finished in 1 hours or the person who finished in 2 hours.",
        "the person who did a puzzle of cats took at least 1 more hours than the person who finished in 1 hours.",
        "the person who did a puzzle of cats took at least 1 less hours than the person who finished in 1 hours.",
        "the person who did a puzzle of cats took some more hours than the person who finished in 1 hours.",
        "the person who did a puzzle of cats is not the person who did the 100 piece puzzle.",
        "the person who did a puzzle of cats is the person who did the 100 piece puzzle or the person who did the 200 piece puzzle.",
        "the person who did a puzzle of cats assembled at least 100 more pieces than the person who did the 100 piece puzzle.",
        "the person who did a puzzle of cats assembled at least 100 less pieces than the person who did the 100 piece puzzle.",
        "the person who did a puzzle of cats assembled some more pieces than the person who did the 100 piece puzzle.",
        "the person who did a puzzle of cats is not Aaron.",
        "the person who did a puzzle of cats is Aaron or Abby.",
        "the house with 1 trees is not Aaron's house.",
        "the house with 1 trees is Aaron's house or Abby's house.",
        "the house with 1 trees is not the red house.",
        "the house with 1 trees is the red house or the orange house.",
        "the house with 1 trees is not the house with the swing.",
        "the house with 1 trees is the house with the swing or the house with the dog.",
        "Aaron's house is not the house with 1 trees.",
        "Aaron's house is the house with 1 trees or the house with 2 trees.",
        "Aaron's house has at least 1 more trees than the house with 1 trees.",
        "Aaron's house has at least 1 less trees than the house with 1 trees.",
        "Aaron's house has some more trees than the house with 1 trees.",
        "Aaron's house is not the red house.",
        "Aaron's house is the red house or the orange house.",
        "Aaron's house is not the house with the swing.",
        "Aaron's house is the house with the swing or the house with the dog.",
        "the red house is not the house with 1 trees.",
        "the red house is the house with 1 trees or the house with 2 trees.",
        "the red house has at least 1 more trees than the house with 1 trees.",
        "the red house has at least 1 less trees than the house with 1 trees.",
        "the red house has some more trees than the house with 1 trees.",
        "the red house is not Aaron's house.",
        "the red house is Aaron's house or Abby's house.",
        "the red house is not the house with the swing.",
        "the red house is the house with the swing or the house with the dog.",
        "the house with the swing is not the house with 1 trees.",
        "the house with the swing is the house with 1 trees or the house with 2 trees.",
        "the house with the swing has at least 1 more trees than the house with 1 trees.",
        "the house with the swing has at least 1 less trees than the house with 1 trees.",
        "the house with the swing has some more trees than the house with 1 trees.",
        "the house with the swing is not Aaron's house.",
        "the house with the swing is Aaron's house or Abby's house.",
        "the house with the swing is not the red house.",
        "the house with the swing is the red house or the orange house.",
        "the person who snacks at 1 o'clock is not the person who takes 10 minutes.",
        "the person who snacks at 1 o'clock is the person who takes 10 minutes or the person who takes 15 minutes.",
        "the person who snacks at 1 o'clock takes at least 10 minutes more than the person who takes 10 minutes.",
        "the person who snacks at 1 o'clock takes at least 10 minutes less than the person who takes 10 minutes.",
        "the person who snacks at 1 o'clock takes some minutes more than the person who takes 10 minutes.",
        "the person who snacks at 1 o'clock is not Aaron.",
        "the person who snacks at 1 o'clock is Aaron or Abby.",
        "the person who snacks at 1 o'clock is not the person with the red cup.",
        "the person who snacks at 1 o'clock is the person with the red cup or the person with the orange cup.",
        "the person who snacks at 1 o'clock is not the person who drinks tea.",
        "the person who snacks at 1 o'clock is the person who drinks tea or the person who drinks coffee.",
        "the person who snacks at 1 o'clock is not the person who eats the apple.",
        "the person who snacks at 1 o'clock is the person who eats the apple or the person who eats the cookie.",
        "the person who takes 10 minutes is not the person who snacks at 1 o'clock.",
        "the person who takes 10 minutes is the person who snacks at 1 o'clock or the person who snacks at 2 o'clock.",
        "the person who takes 10 minutes snacks at least 1 hours later than the person who snacks at 1 o'clock.",
        "the person who takes 10 minutes snacks at least 1 hours earlier than the person who snacks at 1 o'clock.",
        "the person who takes 10 minutes snacks some hours later than the person who snacks at 1 o'clock.",
        "the person who takes 10 minutes is not Aaron.",
        "the person who takes 10 minutes is Aaron or Abby.",
        "the person who takes 10 minutes is not the person with the red cup.",
        "the person who takes 10 minutes is the person with the red cup or the person with the orange cup.",
        "the person who takes 10 minutes is not the person who drinks tea.",
        "the person who takes 10 minutes is the person who drinks tea or the person who drinks coffee.",
        "the person who takes 10 minutes is not the person who eats the apple.",
        "the person who takes 10 minutes is the person who eats the apple or the person who eats the cookie.",
        "Aaron is not the person who snacks at 1 o'clock.",
        "Aaron is the person who snacks at 1 o'clock or the person who snacks at 2 o'clock.",
        "Aaron snacks at least 1 hours later than the person who snacks at 1 o'clock.",
        "Aaron snacks at least 1 hours earlier than the person who snacks at 1 o'clock.",
        "Aaron snacks some hours later than the person who snacks at 1 o'clock.",
        "Aaron is not the person who takes 10 minutes.",
        "Aaron is the person who takes 10 minutes or the person who takes 15 minutes.",
        "Aaron takes at least 10 minutes more than the person who takes 10 minutes.",
        "Aaron takes at least 10 minutes less than the person who takes 10 minutes.",
        "Aaron takes some minutes more than the person who takes 10 minutes.",
        "Aaron is not the person with the red cup.",
        "Aaron is the person with the red cup or the person with the orange cup.",
        "Aaron is not the person who drinks tea.",
        "Aaron is the person who drinks tea or the person who drinks coffee.",
        "Aaron is not the person who eats the apple.",
        "Aaron is the person who eats the apple or the person who eats the cookie.",
        "the person with the red cup is not the person who snacks at 1 o'clock.",
        "the person with the red cup is the person who snacks at 1 o'clock or the person who snacks at 2 o'clock.",
        "the person with the red cup snacks at least 1 hours later than the person who snacks at 1 o'clock.",
        "the person with the red cup snacks at least 1 hours earlier than the person who snacks at 1 o'clock.",
        "the person with the red cup snacks some hours later than the person who snacks at 1 o'clock.",
        "the person with the red cup is not the person who takes 10 minutes.",
        "the person with the red cup is the person who takes 10 minutes or the person who takes 15 minutes.",
        "the person with the red cup takes at least 10 minutes more than the person who takes 10 minutes.",
        "the person with the red cup takes at least 10 minutes less than the person who takes 10 minutes.",
        "the person with the red cup takes some minutes more than the person who takes 10 minutes.",
        "the person with the red cup is not Aaron.",
        "the person with the red cup is Aaron or Abby.",
        "the person with the red cup is not the person who drinks tea.",
        "the person with the red cup is the person who drinks tea or the person who drinks coffee.",
        "the person with the red cup is not the person who eats the apple.",
        "the person with the red cup is the person who eats the apple or the person who eats the cookie.",
        "the person who drinks tea is not the person who snacks at 1 o'clock.",
        "the person who drinks tea is the person who snacks at 1 o'clock or the person who snacks at 2 o'clock.",
        "the person who drinks tea snacks at least 1 hours later than the person who snacks at 1 o'clock.",
        "the person who drinks tea snacks at least 1 hours earlier than the person who snacks at 1 o'clock.",
        "the person who drinks tea snacks some hours later than the person who snacks at 1 o'clock.",
        "the person who drinks tea is not the person who takes 10 minutes.",
        "the person who drinks tea is the person who takes 10 minutes or the person who takes 15 minutes.",
        "the person who drinks tea takes at least 10 minutes more than the person who takes 10 minutes.",
        "the person who drinks tea takes at least 10 minutes less than the person who takes 10 minutes.",
        "the person who drinks tea takes some minutes more than the person who takes 10 minutes.",
        "the person who drinks tea is not Aaron.",
        "the person who drinks tea is Aaron or Abby.",
        "the person who drinks tea is not the person with the red cup.",
        "the person who drinks tea is the person with the red cup or the person with the orange cup.",
        "the person who drinks tea is not the person who eats the apple.",
        "the person who drinks tea is the person who eats the apple or the person who eats the cookie.",
        "the person who eats the apple is not the person who snacks at 1 o'clock.",
        "the person who eats the apple is the person who snacks at 1 o'clock or the person who snacks at 2 o'clock.",
        "the person who eats the apple snacks at least 1 hours later than the person who snacks at 1 o'clock.",
        "the person who eats the apple snacks at least 1 hours earlier than the person who snacks at 1 o'clock.",
        "the person who eats the apple snacks some hours later than the person who snacks at 1 o'clock.",
        "the person who eats the apple is not the person who takes 10 minutes.",
        "the person who eats the apple is the person who takes 10 minutes or the person who takes 15 minutes.",
        "the person who eats the apple takes at least 10 minutes more than the person who takes 10 minutes.",
        "the person who eats the apple takes at least 10 minutes less than the person who takes 10 minutes.",
        "the person who eats the apple takes some minutes more than the person who takes 10 minutes.",
        "the person who eats the apple is not Aaron.",
        "the person who eats the apple is Aaron or Abby.",
        "the person who eats the apple is not the person with the red cup.",
        "the person who eats the apple is the person with the red cup or the person with the orange cup.",
        "the person who eats the apple is not the person who drinks tea.",
        "the person who eats the apple is the person who drinks tea or the person who drinks coffee.",
        "the jewelry that cost 100 dollars is not the jewelry with 1 stones.",
        "the jewelry that cost 100 dollars is the jewelry with 1 stones or the jewelry with 2 stones.",
        "the jewelry that cost 100 dollars has at least 1 more stones than the jewelry with 1 stones.",
        "the jewelry that cost 100 dollars has at least 1 less stones than the jewelry with 1 stones.",
        "the jewelry that cost 100 dollars has some more stones than the jewelry with 1 stones.",
        "the jewelry that cost 100 dollars is not Aaron's jewelry.",
        "the jewelry that cost 100 dollars is Aaron's jewelry or Abby's jewelry.",
        "the jewelry that cost 100 dollars is not the jewelry with the ruby.",
        "the jewelry that cost 100 dollars is the jewelry with the ruby or the jewelry with the emerald.",
        "the jewelry that cost 100 dollars is not the necklace.",
        "the jewelry that cost 100 dollars is the necklace or the brooch.",
        "the jewelry with 1 stones is not the jewelry that cost 100 dollars.",
        "the jewelry with 1 stones is the jewelry that cost 100 dollars or the jewelry that cost 150 dollars.",
        "the jewelry with 1 stones cost at least 100 dollars more than the jewelry that cost 100 dollars.",
        "the jewelry with 1 stones cost at least 100 dollars less than the jewelry that cost 100 dollars.",
        "the jewelry with 1 stones cost some dollars more than the jewelry that cost 100 dollars.",
        "the jewelry with 1 stones is not Aaron's jewelry.",
        "the jewelry with 1 stones is Aaron's jewelry or Abby's jewelry.",
        "the jewelry with 1 stones is not the jewelry with the ruby.",
        "the jewelry with 1 stones is the jewelry with the ruby or the jewelry with the emerald.",
        "the jewelry with 1 stones is not the necklace.",
        "the jewelry with 1 stones is the necklace or the brooch.",
        "Aaron's jewelry is not the jewelry that cost 100 dollars.",
        "Aaron's jewelry is the jewelry that cost 100 dollars or the jewelry that cost 150 dollars.",
        "Aaron's jewelry cost at least 100 dollars more than the jewelry that cost 100 dollars.",
        "Aaron's jewelry cost at least 100 dollars less than the jewelry that cost 100 dollars.",
        "Aaron's jewelry cost some dollars more than the jewelry that cost 100 dollars.",
        "Aaron's jewelry is not the jewelry with 1 stones.",
        "Aaron's jewelry is the jewelry with 1 stones or the jewelry with 2 stones.",
        "Aaron's jewelry has at least 1 more stones than the jewelry with 1 stones.",
        "Aaron's jewelry has at least 1 less stones than the jewelry with 1 stones.",
        "Aaron's jewelry has some more stones than the jewelry with 1 stones.",
        "Aaron's jewelry is not the jewelry with the ruby.",
        "Aaron's jewelry is the jewelry with the ruby or the jewelry with the emerald.",
        "Aaron's jewelry is not the necklace.",
        "Aaron's jewelry is the necklace or the brooch.",
        "the jewelry with the ruby is not the jewelry that cost 100 dollars.",
        "the jewelry with the ruby is the jewelry that cost 100 dollars or the jewelry that cost 150 dollars.",
        "the jewelry with the ruby cost at least 100 dollars more than the jewelry that cost 100 dollars.",
        "the jewelry with the ruby cost at least 100 dollars less than the jewelry that cost 100 dollars.",
        "the jewelry with the ruby cost some dollars more than the jewelry that cost 100 dollars.",
        "the jewelry with the ruby is not the jewelry with 1 stones.",
        "the jewelry with the ruby is the jewelry with 1 stones or the jewelry with 2 stones.",
        "the jewelry with the ruby has at least 1 more stones than the jewelry with 1 stones.",
        "the jewelry with the ruby has at least 1 less stones than the jewelry with 1 stones.",
        "the jewelry with the ruby has some more stones than the jewelry with 1 stones.",
        "the jewelry with the ruby is not Aaron's jewelry.",
        "the jewelry with the ruby is Aaron's jewelry or Abby's jewelry.",
        "the jewelry with the ruby is not the necklace.",
        "the jewelry with the ruby is the necklace or the brooch.",
        "the necklace is not the jewelry that cost 100 dollars.",
        "the necklace is the jewelry that cost 100 dollars or the jewelry that cost 150 dollars.",
        "the necklace cost at least 100 dollars more than the jewelry that cost 100 dollars.",
        "the necklace cost at least 100 dollars less than the jewelry that cost 100 dollars.",
        "the necklace cost some dollars more than the jewelry that cost 100 dollars.",
        "the necklace is not the jewelry with 1 stones.",
        "the necklace is the jewelry with 1 stones or the jewelry with 2 stones.",
        "the necklace has at least 1 more stones than the jewelry with 1 stones.",
        "the necklace has at least 1 less stones than the jewelry with 1 stones.",
        "the necklace has some more stones than the jewelry with 1 stones.",
        "the necklace is not Aaron's jewelry.",
        "the necklace is Aaron's jewelry or Abby's jewelry.",
        "the necklace is not the jewelry with the ruby.",
        "the necklace is the jewelry with the ruby or the jewelry with the emerald.",
        "Aaron is not the person who does their activity for 10 minutes.",
        "Aaron is the person who does their activity for 10 minutes or the person who does their activity for 20 minutes.",
        "Aaron does at least 10 minutes more than the person who does their activity for 10 minutes.",
        "Aaron does at least 10 minutes less than the person who does their activity for 10 minutes.",
        "Aaron does some minutes more than the person who does their activity for 10 minutes.",
        "Aaron is not the person who bakes.",
        "Aaron is the person who bakes or the person who runs.",
        "Aaron is not the person who does their activity on Monday.",
        "Aaron is the person who does their activity on Monday or the person who does their activity on Tuesday.",
        "the person who does their activity for 10 minutes is not Aaron.",
        "the person who does their activity for 10 minutes is Aaron or Abby.",
        "the person who does their activity for 10 minutes is not the person who bakes.",
        "the person who does their activity for 10 minutes is the person who bakes or the person who runs.",
        "the person who does their activity for 10 minutes is not the person who does their activity on Monday.",
        "the person who does their activity for 10 minutes is the person who does their activity on Monday or the person who does their activity on Tuesday.",
        "the person who bakes is not Aaron.",
        "the person who bakes is Aaron or Abby.",
        "the person who bakes is not the person who does their activity for 10 minutes.",
        "the person who bakes is the person who does their activity for 10 minutes or the person who does their activity for 20 minutes.",
        "the person who bakes does at least 10 minutes more than the person who does their activity for 10 minutes.",
        "the person who bakes does at least 10 minutes less than the person who does their activity for 10 minutes.",
        "the person who bakes does some minutes more than the person who does their activity for 10 minutes.",
        "the person who bakes is not the person who does their activity on Monday.",
        "the person who bakes is the person who does their activity on Monday or the person who does their activity on Tuesday.",
        "the person who does their activity on Monday is not Aaron.",
        "the person who does their activity on Monday is Aaron or Abby.",
        "the person who does their activity on Monday is not the person who does their activity for 10 minutes.",
        "the person who does their activity on Monday is the person who does their activity for 10 minutes or the person who does their activity for 20 minutes.",
        "the person who does their activity on Monday does at least 10 minutes more than the person who does their activity for 10 minutes.",
        "the person who does their activity on Monday does at least 10 minutes less than the person who does their activity for 10 minutes.",
        "the person who does their activity on Monday does some minutes more than the person who does their activity for 10 minutes.",
        "the person who does their activity on Monday is not the person who bakes.",
        "the person who does their activity on Monday is the person who bakes or the person who runs.",
        "Ace is not the collie.",
        "Ace is the collie or the labrador.",
        "Ace is not the 1 year old dog.",
        "Ace is the 1 year old dog or the 2 year old dog.",
        "Ace is at least 1 years older than the 1 year old dog.",
        "Ace is at least 1 years younger than the 1 year old dog.",
        "Ace is some years older than the 1 year old dog.",
        "Ace is not the dog with the red leash.",
        "Ace is the dog with the red leash or the dog with the orange leash.",
        "the collie is not Ace.",
        "the collie is Ace or Angel.",
        "the collie is not the 1 year old dog.",
        "the collie is the 1 year old dog or the 2 year old dog.",
        "the collie is at least 1 years older than the 1 year old dog.",
        "the collie is at least 1 years younger than the 1 year old dog.",
        "the collie is some years older than the 1 year old dog.",
        "the collie is not the dog with the red leash.",
        "the collie is the dog with the red leash or the dog with the orange leash.",
        "the 1 year old dog is not Ace.",
        "the 1 year old dog is Ace or Angel.",
        "the 1 year old dog is not the collie.",
        "the 1 year old dog is the collie or the labrador.",
        "the 1 year old dog is not the dog with the red leash.",
        "the 1 year old dog is the dog with the red leash or the dog with the orange leash.",
        "the dog with the red leash is not Ace.",
        "the dog with the red leash is Ace or Angel.",
        "the dog with the red leash is not the collie.",
        "the dog with the red leash is the collie or the labrador.",
        "the dog with the red leash is not the 1 year old dog.",
        "the dog with the red leash is the 1 year old dog or the 2 year old dog.",
        "the dog with the red leash is at least 1 years older than the 1 year old dog.",
        "the dog with the red leash is at least 1 years younger than the 1 year old dog.",
        "the dog with the red leash is some years older than the 1 year old dog.",
        "the sandwich on french bread is not the eggplant sandwich.",
        "the sandwich on french bread is the eggplant sandwich or the tofu sandwich.",
        "the sandwich on french bread is not the sandwich flavored with mayo.",
        "the sandwich on french bread is the sandwich flavored with mayo or the sandwich flavored with hot sauce.",
        "the sandwich on french bread is not the sandwich that cost $7.",
        "the sandwich on french bread is the sandwich that cost $7 or the sandwich that cost $8.",
        "the sandwich on french bread costs at least 7 dollars more than the sandwich that cost $7.",
        "the sandwich on french bread costs at least 7 dollars less than the sandwich that cost $7.",
        "the sandwich on french bread costs some dollars more than the sandwich that cost $7.",
        "the eggplant sandwich is not the sandwich on french bread.",
        "the eggplant sandwich is the sandwich on french bread or the sandwich on sourdough bread.",
        "the eggplant sandwich is not the sandwich flavored with mayo.",
        "the eggplant sandwich is the sandwich flavored with mayo or the sandwich flavored with hot sauce.",
        "the eggplant sandwich is not the sandwich that cost $7.",
        "the eggplant sandwich is the sandwich that cost $7 or the sandwich that cost $8.",
        "the eggplant sandwich costs at least 7 dollars more than the sandwich that cost $7.",
        "the eggplant sandwich costs at least 7 dollars less than the sandwich that cost $7.",
        "the eggplant sandwich costs some dollars more than the sandwich that cost $7.",
        "the sandwich flavored with mayo is not the sandwich on french bread.",
        "the sandwich flavored with mayo is the sandwich on french bread or the sandwich on sourdough bread.",
        "the sandwich flavored with mayo is not the eggplant sandwich.",
        "the sandwich flavored with mayo is the eggplant sandwich or the tofu sandwich.",
        "the sandwich flavored with mayo is not the sandwich that cost $7.",
        "the sandwich flavored with mayo is the sandwich that cost $7 or the sandwich that cost $8.",
        "the sandwich flavored with mayo costs at least 7 dollars more than the sandwich that cost $7.",
        "the sandwich flavored with mayo costs at least 7 dollars less than the sandwich that cost $7.",
        "the sandwich flavored with mayo costs some dollars more than the sandwich that cost $7.",
        "the sandwich that cost $7 is not the sandwich on french bread.",
        "the sandwich that cost $7 is the sandwich on french bread or the sandwich on sourdough bread.",
        "the sandwich that cost $7 is not the eggplant sandwich.",
        "the sandwich that cost $7 is the eggplant sandwich or the tofu sandwich.",
        "the sandwich that cost $7 is not the sandwich flavored with mayo.",
        "the sandwich that cost $7 is the sandwich flavored with mayo or the sandwich flavored with hot sauce.",
        "the person who dressed as a ghost is not Aaron.",
        "the person who dressed as a ghost is Aaron or Abby.",
        "the person who dressed as a ghost is not the person who favors Snickers.",
        "the person who dressed as a ghost is the person who favors Snickers or the person who favors Twix.",
        "the person who dressed as a ghost is not the person who got 5 pieces of candy.",
        "the person who dressed as a ghost is the person who got 5 pieces of candy or the person who got 10 pieces of candy.",
        "the person who dressed as a ghost got at least 5 more pieces than the person who got 5 pieces of candy.",
        "the person who dressed as a ghost got at least 5 fewer pieces than the person who got 5 pieces of candy.",
        "the person who dressed as a ghost got some more pieces than the person who got 5 pieces of candy.",
        "Aaron is not the person who dressed as a ghost.",
        "Aaron is the person who dressed as a ghost or the person who dressed as a vampire.",
        "Aaron is not the person who favors Snickers.",
        "Aaron is the person who favors Snickers or the person who favors Twix.",
        "Aaron is not the person who got 5 pieces of candy.",
        "Aaron is the person who got 5 pieces of candy or the person who got 10 pieces of candy.",
        "Aaron got at least 5 more pieces than the person who got 5 pieces of candy.",
        "Aaron got at least 5 fewer pieces than the person who got 5 pieces of candy.",
        "Aaron got some more pieces than the person who got 5 pieces of candy.",
        "the person who favors Snickers is not the person who dressed as a ghost.",
        "the person who favors Snickers is the person who dressed as a ghost or the person who dressed as a vampire.",
        "the person who favors Snickers is not Aaron.",
        "the person who favors Snickers is Aaron or Abby.",
        "the person who favors Snickers is not the person who got 5 pieces of candy.",
        "the person who favors Snickers is the person who got 5 pieces of candy or the person who got 10 pieces of candy.",
        "the person who favors Snickers got at least 5 more pieces than the person who got 5 pieces of candy.",
        "the person who favors Snickers got at least 5 fewer pieces than the person who got 5 pieces of candy.",
        "the person who favors Snickers got some more pieces than the person who got 5 pieces of candy.",
        "the person who got 5 pieces of candy is not the person who dressed as a ghost.",
        "the person who got 5 pieces of candy is the person who dressed as a ghost or the person who dressed as a vampire.",
        "the person who got 5 pieces of candy is not Aaron.",
        "the person who got 5 pieces of candy is Aaron or Abby.",
        "the person who got 5 pieces of candy is not the person who favors Snickers.",
        "the person who got 5 pieces of candy is the person who favors Snickers or the person who favors Twix.",
        "the person who asked Santa for a puppy is not Aaron.",
        "the person who asked Santa for a puppy is Aaron or Abby.",
        "the person who asked Santa for a puppy is not the person whose gifts were wrapped in candy wrapping paper.",
        "the person who asked Santa for a puppy is the person whose gifts were wrapped in candy wrapping paper or the person whose gifts were wrapped in reindeer wrapping paper.",
        "the person who asked Santa for a puppy is not the person who received 1 gifts.",
        "the person who asked Santa for a puppy is the person who received 1 gifts or the person who received 2 gifts.",
        "the person who asked Santa for a puppy received at least 1 more gifts than the person who received 1 gifts.",
        "the person who asked Santa for a puppy received at least 1 fewer gifts than the person who received 1 gifts.",
        "the person who asked Santa for a puppy received some more gifts than the person who received 1 gifts.",
        "Aaron is not the person who asked Santa for a puppy.",
        "Aaron is the person who asked Santa for a puppy or the person who asked Santa for a pony.",
        "Aaron is not the person whose gifts were wrapped in candy wrapping paper.",
        "Aaron is the person whose gifts were wrapped in candy wrapping paper or the person whose gifts were wrapped in reindeer wrapping paper.",
        "Aaron is not the person who received 1 gifts.",
        "Aaron is the person who received 1 gifts or the person who received 2 gifts.",
        "Aaron received at least 1 more gifts than the person who received 1 gifts.",
        "Aaron received at least 1 fewer gifts than the person who received 1 gifts.",
        "Aaron received some more gifts than the person who received 1 gifts.",
        "the person whose gifts were wrapped in candy wrapping paper is not the person who asked Santa for a puppy.",
        "the person whose gifts were wrapped in candy wrapping paper is the person who asked Santa for a puppy or the person who asked Santa for a pony.",
        "the person whose gifts were wrapped in candy wrapping paper is not Aaron.",
        "the person whose gifts were wrapped in candy wrapping paper is Aaron or Abby.",
        "the person whose gifts were wrapped in candy wrapping paper is not the person who received 1 gifts.",
        "the person whose gifts were wrapped in candy wrapping paper is the person who received 1 gifts or the person who received 2 gifts.",
        "the person whose gifts were wrapped in candy wrapping paper received at least 1 more gifts than the person who received 1 gifts.",
        "the person whose gifts were wrapped in candy wrapping paper received at least 1 fewer gifts than the person who received 1 gifts.",
        "the person whose gifts were wrapped in candy wrapping paper received some more gifts than the person who received 1 gifts.",
        "the person who received 1 gifts is not the person who asked Santa for a puppy.",
        "the person who received 1 gifts is the person who asked Santa for a puppy or the person who asked Santa for a pony.",
        "the person who received 1 gifts is not Aaron.",
        "the person who received 1 gifts is Aaron or Abby.",
        "the person who received 1 gifts is not the person whose gifts were wrapped in candy wrapping paper.",
        "the person who received 1 gifts is the person whose gifts were wrapped in candy wrapping paper or the person whose gifts were wrapped in reindeer wrapping paper.",
        "the historian who studies disease is not Aaron.",
        "the historian who studies disease is Aaron or Abby.",
        "the historian who studies disease is not the historian who studies at Stanford.",
        "the historian who studies disease is the historian who studies at Stanford or the historian who studies at Harvard.",
        "the historian who studies disease is not the historian who studies the 14th century.",
        "the historian who studies disease is the historian who studies the 14th century or the historian who studies the 15th century.",
        "the historian who studies disease studies the period at least 14 centuries later than the historian who studies the 14th century.",
        "the historian who studies disease studies the period at least 14 centuries earlier than the historian who studies the 14th century.",
        "the historian who studies disease studies the period some centuries later than the historian who studies the 14th century.",
        "Aaron is not the historian who studies disease.",
        "Aaron is the historian who studies disease or the historian who studies wealth.",
        "Aaron is not the historian who studies at Stanford.",
        "Aaron is the historian who studies at Stanford or the historian who studies at Harvard.",
        "Aaron is not the historian who studies the 14th century.",
        "Aaron is the historian who studies the 14th century or the historian who studies the 15th century.",
        "Aaron studies the period at least 14 centuries later than the historian who studies the 14th century.",
        "Aaron studies the period at least 14 centuries earlier than the historian who studies the 14th century.",
        "Aaron studies the period some centuries later than the historian who studies the 14th century.",
        "the historian who studies at Stanford is not the historian who studies disease.",
        "the historian who studies at Stanford is the historian who studies disease or the historian who studies wealth.",
        "the historian who studies at Stanford is not Aaron.",
        "the historian who studies at Stanford is Aaron or Abby.",
        "the historian who studies at Stanford is not the historian who studies the 14th century.",
        "the historian who studies at Stanford is the historian who studies the 14th century or the historian who studies the 15th century.",
        "the historian who studies at Stanford studies the period at least 14 centuries later than the historian who studies the 14th century.",
        "the historian who studies at Stanford studies the period at least 14 centuries earlier than the historian who studies the 14th century.",
        "the historian who studies at Stanford studies the period some centuries later than the historian who studies the 14th century.",
        "the historian who studies the 14th century is not the historian who studies disease.",
        "the historian who studies the 14th century is the historian who studies disease or the historian who studies wealth.",
        "the historian who studies the 14th century is not Aaron.",
        "the historian who studies the 14th century is Aaron or Abby.",
        "the historian who studies the 14th century is not the historian who studies at Stanford.",
        "the historian who studies the 14th century is the historian who studies at Stanford or the historian who studies at Harvard.",
        "the fir tree is not the tree that is known for its height.",
        "the fir tree is the tree that is known for its height or the tree that is known for its width.",
        "the fir tree is not the tree in Alabama.",
        "the fir tree is the tree in Alabama or the tree in Alaska.",
        "the fir tree is not the 10 year old tree.",
        "the fir tree is the 10 year old tree or the 20 year old tree.",
        "the fir tree is at least 10 years older than the 10 year old tree.",
        "the fir tree is at least 10 years younger than the 10 year old tree.",
        "the fir tree is some years older than the 10 year old tree.",
        "the tree that is known for its height is not the fir tree.",
        "the tree that is known for its height is the fir tree or the oak tree.",
        "the tree that is known for its height is not the tree in Alabama.",
        "the tree that is known for its height is the tree in Alabama or the tree in Alaska.",
        "the tree that is known for its height is not the 10 year old tree.",
        "the tree that is known for its height is the 10 year old tree or the 20 year old tree.",
        "the tree that is known for its height is at least 10 years older than the 10 year old tree.",
        "the tree that is known for its height is at least 10 years younger than the 10 year old tree.",
        "the tree that is known for its height is some years older than the 10 year old tree.",
        "the tree in Alabama is not the fir tree.",
        "the tree in Alabama is the fir tree or the oak tree.",
        "the tree in Alabama is not the tree that is known for its height.",
        "the tree in Alabama is the tree that is known for its height or the tree that is known for its width.",
        "the tree in Alabama is not the 10 year old tree.",
        "the tree in Alabama is the 10 year old tree or the 20 year old tree.",
        "the tree in Alabama is at least 10 years older than the 10 year old tree.",
        "the tree in Alabama is at least 10 years younger than the 10 year old tree.",
        "the tree in Alabama is some years older than the 10 year old tree.",
        "the 10 year old tree is not the fir tree.",
        "the 10 year old tree is the fir tree or the oak tree.",
        "the 10 year old tree is not the tree that is known for its height.",
        "the 10 year old tree is the tree that is known for its height or the tree that is known for its width.",
        "the 10 year old tree is not the tree in Alabama.",
        "the 10 year old tree is the tree in Alabama or the tree in Alaska.",
        "the person who came in 1st is not the person wearing the red jersey.",
        "the person who came in 1st is the person wearing the red jersey or the person wearing the orange jersey.",
        "the person who came in 1st is not Aaron.",
        "the person who came in 1st is Aaron or Abby.",
        "the person who came in 1st is not the person who ran the 50 meter race.",
        "the person who came in 1st is the person who ran the 50 meter race or the person who ran the 100 meter race.",
        "the person who came in 1st raced at least 50 meters more than the person who ran the 50 meter race.",
        "the person who came in 1st raced at least 50 meters less than the person who ran the 50 meter race.",
        "the person who came in 1st raced some meters more than the person who ran the 50 meter race.",
        "the person wearing the red jersey is not the person who came in 1st.",
        "the person wearing the red jersey is the person who came in 1st or the person who came in 2nd.",
        "the person wearing the red jersey placed at least 1 places worse than the person who came in 1st.",
        "the person wearing the red jersey placed at least 1 places better than the person who came in 1st.",
        "the person wearing the red jersey placed some places worse than the person who came in 1st.",
        "the person wearing the red jersey is not Aaron.",
        "the person wearing the red jersey is Aaron or Abby.",
        "the person wearing the red jersey is not the person who ran the 50 meter race.",
        "the person wearing the red jersey is the person who ran the 50 meter race or the person who ran the 100 meter race.",
        "the person wearing the red jersey raced at least 50 meters more than the person who ran the 50 meter race.",
        "the person wearing the red jersey raced at least 50 meters less than the person who ran the 50 meter race.",
        "the person wearing the red jersey raced some meters more than the person who ran the 50 meter race.",
        "Aaron is not the person who came in 1st.",
        "Aaron is the person who came in 1st or the person who came in 2nd.",
        "Aaron placed at least 1 places worse than the person who came in 1st.",
        "Aaron placed at least 1 places better than the person who came in 1st.",
        "Aaron placed some places worse than the person who came in 1st.",
        "Aaron is not the person wearing the red jersey.",
        "Aaron is the person wearing the red jersey or the person wearing the orange jersey.",
        "Aaron is not the person who ran the 50 meter race.",
        "Aaron is the person who ran the 50 meter race or the person who ran the 100 meter race.",
        "Aaron raced at least 50 meters more than the person who ran the 50 meter race.",
        "Aaron raced at least 50 meters less than the person who ran the 50 meter race.",
        "Aaron raced some meters more than the person who ran the 50 meter race.",
        "the person who ran the 50 meter race is not the person who came in 1st.",
        "the person who ran the 50 meter race is the person who came in 1st or the person who came in 2nd.",
        "the person who ran the 50 meter race placed at least 1 places worse than the person who came in 1st.",
        "the person who ran the 50 meter race placed at least 1 places better than the person who came in 1st.",
        "the person who ran the 50 meter race placed some places worse than the person who came in 1st.",
        "the person who ran the 50 meter race is not the person wearing the red jersey.",
        "the person who ran the 50 meter race is the person wearing the red jersey or the person wearing the orange jersey.",
        "the person who ran the 50 meter race is not Aaron.",
        "the person who ran the 50 meter race is Aaron or Abby.",
        "the person vacationed for 1 days is not the person who traveled to Belgium.",
        "the person vacationed for 1 days is the person who traveled to Belgium or the person who traveled to Croatia.",
        "the person vacationed for 1 days is not the person who flew on Skyway airline.",
        "the person vacationed for 1 days is the person who flew on Skyway airline or the person who flew on Aero airline.",
        "the person vacationed for 1 days is not the person who took their trip in January.",
        "the person vacationed for 1 days is the person who took their trip in January or the person who took their trip in February.",
        "the person vacationed for 1 days is not the person who started their trip on Monday.",
        "the person vacationed for 1 days is the person who started their trip on Monday or the person who started their trip on Tuesday.",
        "the person who traveled to Belgium is not the person vacationed for 1 days.",
        "the person who traveled to Belgium is the person vacationed for 1 days or the person vacationed for 2 days.",
        "the person who traveled to Belgium vacationed at least 1 more days than the person vacationed for 1 days.",
        "the person who traveled to Belgium vacationed at least 1 less days than the person vacationed for 1 days.",
        "the person who traveled to Belgium vacationed some more days than the person vacationed for 1 days.",
        "the person who traveled to Belgium is not the person who flew on Skyway airline.",
        "the person who traveled to Belgium is the person who flew on Skyway airline or the person who flew on Aero airline.",
        "the person who traveled to Belgium is not the person who took their trip in January.",
        "the person who traveled to Belgium is the person who took their trip in January or the person who took their trip in February.",
        "the person who traveled to Belgium is not the person who started their trip on Monday.",
        "the person who traveled to Belgium is the person who started their trip on Monday or the person who started their trip on Tuesday.",
        "the person who flew on Skyway airline is not the person vacationed for 1 days.",
        "the person who flew on Skyway airline is the person vacationed for 1 days or the person vacationed for 2 days.",
        "the person who flew on Skyway airline vacationed at least 1 more days than the person vacationed for 1 days.",
        "the person who flew on Skyway airline vacationed at least 1 less days than the person vacationed for 1 days.",
        "the person who flew on Skyway airline vacationed some more days than the person vacationed for 1 days.",
        "the person who flew on Skyway airline is not the person who traveled to Belgium.",
        "the person who flew on Skyway airline is the person who traveled to Belgium or the person who traveled to Croatia.",
        "the person who flew on Skyway airline is not the person who took their trip in January.",
        "the person who flew on Skyway airline is the person who took their trip in January or the person who took their trip in February.",
        "the person who flew on Skyway airline is not the person who started their trip on Monday.",
        "the person who flew on Skyway airline is the person who started their trip on Monday or the person who started their trip on Tuesday.",
        "the person who took their trip in January is not the person vacationed for 1 days.",
        "the person who took their trip in January is the person vacationed for 1 days or the person vacationed for 2 days.",
        "the person who took their trip in January vacationed at least 1 more days than the person vacationed for 1 days.",
        "the person who took their trip in January vacationed at least 1 less days than the person vacationed for 1 days.",
        "the person who took their trip in January vacationed some more days than the person vacationed for 1 days.",
        "the person who took their trip in January is not the person who traveled to Belgium.",
        "the person who took their trip in January is the person who traveled to Belgium or the person who traveled to Croatia.",
        "the person who took their trip in January is not the person who flew on Skyway airline.",
        "the person who took their trip in January is the person who flew on Skyway airline or the person who flew on Aero airline.",
        "the person who took their trip in January is not the person who started their trip on Monday.",
        "the person who took their trip in January is the person who started their trip on Monday or the person who started their trip on Tuesday.",
        "the person who started their trip on Monday is not the person vacationed for 1 days.",
        "the person who started their trip on Monday is the person vacationed for 1 days or the person vacationed for 2 days.",
        "the person who started their trip on Monday vacationed at least 1 more days than the person vacationed for 1 days.",
        "the person who started their trip on Monday vacationed at least 1 less days than the person vacationed for 1 days.",
        "the person who started their trip on Monday vacationed some more days than the person vacationed for 1 days.",
        "the person who started their trip on Monday is not the person who traveled to Belgium.",
        "the person who started their trip on Monday is the person who traveled to Belgium or the person who traveled to Croatia.",
        "the person who started their trip on Monday is not the person who flew on Skyway airline.",
        "the person who started their trip on Monday is the person who flew on Skyway airline or the person who flew on Aero airline.",
        "the person who started their trip on Monday is not the person who took their trip in January.",
        "the person who started their trip on Monday is the person who took their trip in January or the person who took their trip in February.",
        "Ace is not the pet with 0 legs.",
        "Ace is the pet with 0 legs or the pet with 2 legs.",
        "Ace has at least 0 more legs than the pet with 0 legs.",
        "Ace has at least 0 fewer legs than the pet with 0 legs.",
        "Ace has some more legs than the pet with 0 legs.",
        "Ace is not the pet that likes sleeping.",
        "Ace is the pet that likes sleeping or the pet that likes hiding.",
        "Ace is not the pet in the metal cage.",
        "Ace is the pet in the metal cage or the pet in the glass cage.",
        "the pet with 0 legs is not Ace.",
        "the pet with 0 legs is Ace or Angel.",
        "the pet with 0 legs is not the pet that likes sleeping.",
        "the pet with 0 legs is the pet that likes sleeping or the pet that likes hiding.",
        "the pet with 0 legs is not the pet in the metal cage.",
        "the pet with 0 legs is the pet in the metal cage or the pet in the glass cage.",
        "the pet that likes sleeping is not Ace.",
        "the pet that likes sleeping is Ace or Angel.",
        "the pet that likes sleeping is not the pet with 0 legs.",
        "the pet that likes sleeping is the pet with 0 legs or the pet with 2 legs.",
        "the pet that likes sleeping has at least 0 more legs than the pet with 0 legs.",
        "the pet that likes sleeping has at least 0 fewer legs than the pet with 0 legs.",
        "the pet that likes sleeping has some more legs than the pet with 0 legs.",
        "the pet that likes sleeping is not the pet in the metal cage.",
        "the pet that likes sleeping is the pet in the metal cage or the pet in the glass cage.",
        "the pet in the metal cage is not Ace.",
        "the pet in the metal cage is Ace or Angel.",
        "the pet in the metal cage is not the pet with 0 legs.",
        "the pet in the metal cage is the pet with 0 legs or the pet with 2 legs.",
        "the pet in the metal cage has at least 0 more legs than the pet with 0 legs.",
        "the pet in the metal cage has at least 0 fewer legs than the pet with 0 legs.",
        "the pet in the metal cage has some more legs than the pet with 0 legs.",
        "the pet in the metal cage is not the pet that likes sleeping.",
        "the pet in the metal cage is the pet that likes sleeping or the pet that likes hiding.",
        "the clown with the red hair is not the clown on 0 wheels.",
        "the clown with the red hair is the clown on 0 wheels or the clown on 1 wheels.",
        "the clown with the red hair rides on at least 0 more wheels than the clown on 0 wheels.",
        "the clown with the red hair rides on at least 0 fewer wheels than the clown on 0 wheels.",
        "the clown with the red hair rides on some more wheels than the clown on 0 wheels.",
        "the clown with the red hair is not the clown that juggles.",
        "the clown with the red hair is the clown that juggles or the clown that sings.",
        "the clown with the red hair is not the clown with the flower.",
        "the clown with the red hair is the clown with the flower or the clown with the hose.",
        "the clown on 0 wheels is not the clown with the red hair.",
        "the clown on 0 wheels is the clown with the red hair or the clown with the orange hair.",
        "the clown on 0 wheels is not the clown that juggles.",
        "the clown on 0 wheels is the clown that juggles or the clown that sings.",
        "the clown on 0 wheels is not the clown with the flower.",
        "the clown on 0 wheels is the clown with the flower or the clown with the hose.",
        "the clown that juggles is not the clown with the red hair.",
        "the clown that juggles is the clown with the red hair or the clown with the orange hair.",
        "the clown that juggles is not the clown on 0 wheels.",
        "the clown that juggles is the clown on 0 wheels or the clown on 1 wheels.",
        "the clown that juggles rides on at least 0 more wheels than the clown on 0 wheels.",
        "the clown that juggles rides on at least 0 fewer wheels than the clown on 0 wheels.",
        "the clown that juggles rides on some more wheels than the clown on 0 wheels.",
        "the clown that juggles is not the clown with the flower.",
        "the clown that juggles is the clown with the flower or the clown with the hose.",
        "the clown with the flower is not the clown with the red hair.",
        "the clown with the flower is the clown with the red hair or the clown with the orange hair.",
        "the clown with the flower is not the clown on 0 wheels.",
        "the clown with the flower is the clown on 0 wheels or the clown on 1 wheels.",
        "the clown with the flower rides on at least 0 more wheels than the clown on 0 wheels.",
        "the clown with the flower rides on at least 0 fewer wheels than the clown on 0 wheels.",
        "the clown with the flower rides on some more wheels than the clown on 0 wheels.",
        "the clown with the flower is not the clown that juggles.",
        "the clown with the flower is the clown that juggles or the clown that sings.",
      ]
    `);
  });
});
